// Elite Sport - بيانات المنتجات (للعرض فقط)
// صور منتجات عادية — بدون صور بنات

window.ELITE_SPORT_PRODUCTS = [
  {
    id: "es-men-elite-tee",
    name: "تيشيرت جري Elite Dry-Fit",
    category: "men",
    price: 189,
    sizes: ["S", "M", "L", "XL"],
    featured: true,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
    description: "تيشيرت جري احترافي بخامة Dry-Fit، تهوية عالية، مثالي للجري والتمارين.",
  },
  {
    id: "es-men-compression-top",
    name: "تيشيرت ضغط Elite Pro",
    category: "men",
    price: 229,
    sizes: ["M", "L", "XL"],
    featured: true,
    image: "image2.png",
    description: "تيشيرت ضغط يدعم العضلات ويقلل الاهتزاز، قصّة مخصصة للرياضيين.",
  },
  {
    id: "es-shoes-sprint-red",
    name: "حذاء جري Elite Sprint",
    category: "shoes",
    price: 449,
    sizes: ["42", "43", "44"],
    featured: true,
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
    description: "حذاء جري خفيف الوزن مع توسيد متقدم، ألوان حمراء رياضية.",
  },
  {
    id: "es-set-training-black",
    name: "طقم تدريب Elite Performance أسود",
    category: "sets",
    price: 379,
    sizes: ["S", "M", "L", "XL"],
    featured: false,
    image: "image.png",
    description: "طقم تدريب متكامل بخامة مرنة، تشطيب معدني أنيق.",
  },
  {
    id: "es-access-band-red",
    name: "رباط معصم Elite",
    category: "accessories",
    price: 69,
    sizes: ["S", "M"],
    featured: false,
    image: "image3.png",
    description: "رباط معصم بامتصاص عالي للعرق، مثالي للجيم والجري.",
  },
  {
    id: "es-access-pro-bag",
    name: "حقيبة صالة Elite Pro",
    category: "accessories",
    price: 259,
    sizes: [],
    featured: false,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    description: "حقيبة صالة واسعة مع جيوب متعددة وحماية للأحذية.",
  },
];
